Type: Jupyter Notebook Extension
Compatibility: 3.x, 4.x, 5.x, 6.x
Name: stripcommon
Main: main.js
Link: README.md
Description: |
  Strips common whitespace from lines pasted into a cell
Parameters:
- none